

# source files in this project (main.cpp is automatically assumed)
SOURCES :=

# header files in this project
HEADERS := display.hpp InitGameControl.hpp KeyPad.hpp RunGameControl.hpp receive.hpp send.hpp Registergame.hpp

# other places to look for files for this project
SEARCH  := 

# set RELATIVE to the next higher directory and defer to the Makefile.due
RELATIVE := $(RELATIVE)../
include $(RELATIVE)Makefile.due
